Folllowing and understaning someone's solution!

In [1]:
import numpy as np # Linear Algebra
import pandas as pd # Data Processing

import os
for dirname, _, filenames in os.walk('input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [2]:
train = pd.read_csv('../data/input/demand-forecasting-kernels-only/train.csv')
test = pd.read_csv('../data/input/demand-forecasting-kernels-only/test.csv')
sample = pd.read_csv('../data/input/demand-forecasting-kernels-only/sample_submission.csv')

In [3]:
train.head()

date  store  item  sales
0  2013-01-01      1     1     13
1  2013-01-02      1     1     11
2  2013-01-03      1     1     14
3  2013-01-04      1     1     13
4  2013-01-05      1     1     10

In [4]:
train.isnull().sum().sum()
# two .sum() calsulaes the total count of NaNs across all columns in the DataFrame

np.int64(0)

In [5]:
test.drop("id", axis=1, inplace=True)

In [6]:
train.shape, test.shape

((913000, 4), (45000, 3))

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 913000 entries, 0 to 912999
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   date    913000 non-null  object
 1   store   913000 non-null  int64 
 2   item    913000 non-null  int64 
 3   sales   913000 non-null  int64 
dtypes: int64(3), object(1)
memory usage: 27.9+ MB


In [9]:
train["date"] = pd.to_datetime(train["date"])
train["Day"] = train["date"].dt.day
train["Month"] = train["date"].dt.month
train["Years"] = train["date"].dt.year
train.drop("date", axis=1, inplace=True)

In [10]:
test["date"] = pd.to_datetime(test["date"])
test["Day"] = test["date"].dt.day
test["Month"] = test["date"].dt.month
test["Years"] = test["date"].dt.year
test.drop("date", axis=1, inplace=True)

In [11]:
train.head()

store  item  sales  Day  Month  Years
0      1     1     13    1      1   2013
1      1     1     11    2      1   2013
2      1     1     14    3      1   2013
3      1     1     13    4      1   2013
4      1     1     10    5      1   2013

In [12]:
train["store"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
train["sales"].unique()

array([ 13,  11,  14,  10,  12,   9,   7,   5,  16,  18,  15,   8,   6,
        21,  20,  17,  22,  19,  24,  23,  26,  25,  27,  38,  34,  29,
        31,  30,   4,  36,  28,  33,  32,  37,  35,  43,  40,  41,  39,
        42,  50,  45,  44,  47,  53,  49,  46,  48,  51,  58,  54,  57,
        55,  52,   3,   2,   1,  59,  56,  60,  63,  69,  64,  67,  65,
        71,  61,  73,  62,  82,  78,  68,  74,  70,  87,  66,  77,  88,
        76,  75, 102,  72,  92,  86,  79,  85,  81,  90,  84,  80, 103,
        97,  96,  95,  89, 104,  94, 100,  91,  83, 106, 101,  98, 115,
        93, 111, 119,  99, 108, 110, 120, 105, 126, 109, 114, 113, 112,
       121, 107, 117, 118, 139, 124, 131, 123, 138, 134, 127, 136, 116,
       125, 122, 128, 150, 129, 135, 137, 132, 133, 145, 130, 144,   0,
       148, 141, 140, 152, 147, 169, 156, 159, 153, 142, 157, 155, 163,
       143, 154, 165, 146, 160, 158, 151, 164, 171, 161, 177, 162, 175,
       181, 168, 167, 149, 174, 170, 176, 178, 166, 173, 187, 18

In [14]:
X_train = train.drop(['sales'], axis=1)
y_train = train['sales']

In [15]:
X_test = train.drop(['sales'], axis=1)
y_test = train['sales']

In [16]:
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.tree import ExtraTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.linear_model import LinearRegression, ElasticNet, Ridge, Lasso
from sklearn.metrics import r2_score, mean_squared_error,mean_absolute_error
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor

In [17]:
def regression_algo(x,y):
    
    L = LinearRegression()
# finds the best straight line to fit the data, predicting a continuous output based on input features.
    E = ElasticNet()
# ombines Lasso and Ridge regression, useful for variable selection and handling correlated features.
    R = Ridge()
# adds a penalty to the size of coefficients, helping prevent overfitting, especially with many features.
    Lass = Lasso()
#  adds a penalty, but it can shrink some coefficients exactly to zero, effectively performing feature selection.
    ETR=ExtraTreeRegressor()
#  builds many decision trees, similar to Random Forest, but with an added layer of randomness in how it splits the data, often leading to faster training and good performance.
    GBR=GradientBoostingRegressor()
# builds a strong predictive model by sequentially combining many weak models (like small decision trees), with each new model correcting the errors of the previous ones.
    XGBC= XGBRegressor()
# is an optimized and highly efficient version of Gradient Boosting, known for its speed and top-tier performance in many machine learning competitions.
    RFR=RandomForestRegressor()
#  creates many decision trees during training and outputs the average prediction of all individual trees, reducing overfitting and improving accuracy.
          
    x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=13)
    
    algos = [L,E,R,Lass,ETR,GBR,XGBC,RFR]
    algo_names = ['Linear','ElasticNet','Ridge','Lasso','Extra Tree','Gradient Boosting','XGradientBooting','Random Forest']
    r_squared = []
    rmse = []
    mae = []
        
    result = pd.DataFrame(columns = ['R_Squared','RMSE','MAE'],index = algo_names)
       
    for algo in algos:
        algo.fit(x_train,y_train)
             
        r_squared.append(r2_score(y_test,algo.predict(x_test)))
        rmse.append(mean_squared_error(y_test, algo.predict(x_test))**.5)
        mae.append(mean_absolute_error(y_test, algo.predict(x_test)))

    result.R_Squared = r_squared
    result.RMSE = rmse
    result.MAE= mae
    
    result = result.sort_values('R_Squared', ascending=False).round(2)
    return result.applymap(lambda x: f"{x:.2f}")

In [19]:
regression_algo(X_train,y_train) 

C:\Users\Parsan Afzar\AppData\Local\Temp\ipykernel_896\1043901589.py:42: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  return result.applymap(lambda x: f"{x:.2f}")


R_Squared   RMSE    MAE
XGradientBooting       0.88  10.00   7.52
Random Forest          0.85  11.16   8.24
Extra Tree             0.73  14.90  10.83
Gradient Boosting      0.68  16.26  12.27
Ridge                  0.04  28.16  22.62
Linear                 0.04  28.16  22.62
Lasso                  0.04  28.17  22.63
ElasticNet             0.04  28.19  22.64

In [20]:
GBR = GradientBoostingRegressor()
GBRmodel = GBR.fit(X_train, y_train)

In [22]:
pred = GBR.predict(test)
pred

array([13.70504854, 13.70504854, 13.70504854, ..., 66.39925593,
       66.39925593, 66.39925593], shape=(45000,))

In [23]:
sample.head()

id  sales
0   0     52
1   1     52
2   2     52
3   3     52
4   4     52

In [24]:
submission_ids= sample['id']
submission = pd.DataFrame({'id': submission_ids, 'sales': pred})
submission.to_csv('submission.csv', index=False)
submission

id      sales
0          0  13.705049
1          1  13.705049
2          2  13.705049
3          3  13.705049
4          4  13.705049
...      ...        ...
44995  44995  66.399256
44996  44996  66.399256
44997  44997  66.399256
44998  44998  66.399256
44999  44999  66.399256

[45000 rows x 2 columns]